In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from datetime import datetime
import os

os.getcwd()
os.chdir("CSV-Data")

In [13]:
df = pd.read_csv("DeIdentified_Vizient_Data_New.csv")
df

,organization,cohort date,nurse id,deid_names,employment start date,type of unit,age,gender,education,nursing degree received,...,previous health care work experience,leave,type of leave,termination,termination date,tenure,termination reason,termination updated by,education (cleaned),id
0,Emory University Hospital Midtown,\t08/28/2025,\t0479886,13695,08/04/2025,Oncology Inpatient Unit,37.0,Female,\t37,BSN,...,Nursing assistive personnel (Nursing assistant...,No,NaN,No,NaN,NaN,NaN,NaN,\t37,20575
1,Emory University Hospital Midtown,\t08/08/2025,\t0480100,13696,08/04/2025,Medical/Surgical Inpatient Unit,23.0,Female,Albany State University,BSN,...,NaN,No,NaN,No,NaN,NaN,NaN,NaN,Albany State University,20576
2,Emory University Hospital Midtown,\t10/24/2025,\t0471803,12881,11/17/2025,Cardiac/Heart/Vascular Critical Care,51.0,Female,Abraham Baldwin Agricultural College,ADN/ASN,...,NaN,No,NaN,No,NaN,NaN,NaN,NaN,Abraham Baldwin Agricultural College,18561
3,Emory Saint Joseph’s Hospital,\t10/02/2025,\t2602393,13698,09/29/2025,Medical/Surgical Inpatient Unit,25.0,Female,Abraham Baldwin Agricultural College,ADN/ASN,...,Extern/Intern,No,NaN,No,NaN,NaN,NaN,NaN,Abraham Baldwin Agricultural College,20577
4,Emory Saint Joseph’s Hospital,\t07/18/2022,\t0456040,13699,08/01/2022,Orthopedic Inpatient Unit,29.0,Female,Abraham Baldwin Agricultural College,ADN/ASN,...,NaN,No,NaN,Yes,01/13/2023,0.452055,Unsatisfactory performance,donna.alvarez@emoryhealthcare.org,Abraham Baldwin Agricultural College,20578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5220,Emory Decatur Hospital,\t03/28/2023,\t0427915,18915,03/21/2023,Rehabilitation Inpatient Unit,50.0,Female,Xavier university,Accelerated BSN,...,NaN,No,NaN,No,NaN,NaN,NaN,NaN,Xavier University,25789
5221,Emory University Hospital Midtown,\t08/13/2021,\t0448626,18916,08/09/2021,General Medical Inpatient Unit,22.0,Female,xavier university,BSN,...,NaN,No,NaN,No,NaN,NaN,NaN,NaN,Xavier University,25790
5222,Emory Saint Joseph’s Hospital,\t07/15/2019,\t0436135,18917,07/15/2019,Medical/Surgical Intermediate Unit,24.0,Female,Xavier University,BSN,...,NaN,No,NaN,Yes,09/14/2020,1.169863,Relocating out of area,heather.lachiewicz@emoryhealthcare.o,Xavier University,25791
5223,Emory University Hospital,\t02/24/2017,\t647963,18918,NaN,Medical/Surgical Inpatient Unit,30.0,Female,Xavier University of Louisiana,BSN,...,NaN,No,NaN,No,NaN,NaN,NaN,NaN,Xavier University Of Louisiana,25792
5224,Emory University Hospital Midtown,\t10/25/2024,\t0474420,18919,10/14/2024,Orthopedic Inpatient Unit,39.0,Female,York technical college,ADN/ASN,...,NaN,No,NaN,No,NaN,NaN,NaN,NaN,York Technical College,25793

In [19]:
df_clean = df.copy()
df_clean

,organization,cohort date,nurse id,deid_names,employment start date,type of unit,age,gender,education,nursing degree received,...,previous health care work experience,leave,type of leave,termination,termination date,tenure,termination reason,termination updated by,education (cleaned),id
0,Emory University Hospital Midtown,2025-08-28,0479886,13695,2025-08-04,Oncology Inpatient Unit,37.0,Female,37,Bsn,...,Nursing Assistive Personnel (Nursing Assistant...,No,<NA>,No,NaT,NaN,<NA>,<NA>,37,20575
1,Emory University Hospital Midtown,2025-08-08,0480100,13696,2025-08-04,Medical/Surgical Inpatient Unit,23.0,Female,Albany State University,Bsn,...,<NA>,No,<NA>,No,NaT,NaN,<NA>,<NA>,Albany State University,20576
2,Emory University Hospital Midtown,2025-10-24,0471803,12881,2025-11-17,Cardiac/Heart/Vascular Critical Care,51.0,Female,Abraham Baldwin Agricultural College,Adn/Asn,...,<NA>,No,<NA>,No,NaT,NaN,<NA>,<NA>,Abraham Baldwin Agricultural College,18561
3,Emory Saint Joseph’S Hospital,2025-10-02,2602393,13698,2025-09-29,Medical/Surgical Inpatient Unit,25.0,Female,Abraham Baldwin Agricultural College,Adn/Asn,...,Extern/Intern,No,<NA>,No,NaT,NaN,<NA>,<NA>,Abraham Baldwin Agricultural College,20577
4,Emory Saint Joseph’S Hospital,2022-07-18,0456040,13699,2022-08-01,Orthopedic Inpatient Unit,29.0,Female,Abraham Baldwin Agricultural College,Adn/Asn,...,<NA>,No,<NA>,Yes,2023-01-13,0.452055,Unsatisfactory Performance,donna.alvarez@emoryhealthcare.org,Abraham Baldwin Agricultural College,20578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5220,Emory Decatur Hospital,2023-03-28,0427915,18915,2023-03-21,Rehabilitation Inpatient Unit,50.0,Female,Xavier University,Accelerated Bsn,...,<NA>,No,<NA>,No,NaT,NaN,<NA>,<NA>,Xavier University,25789
5221,Emory University Hospital Midtown,2021-08-13,0448626,18916,2021-08-09,General Medical Inpatient Unit,22.0,Female,Xavier University,Bsn,...,<NA>,No,<NA>,No,NaT,NaN,<NA>,<NA>,Xavier University,25790
5222,Emory Saint Joseph’S Hospital,2019-07-15,0436135,18917,2019-07-15,Medical/Surgical Intermediate Unit,24.0,Female,Xavier University,Bsn,...,<NA>,No,<NA>,Yes,2020-09-14,1.169863,Relocating Out Of Area,heather.lachiewicz@emoryhealthcare.o,Xavier University,25791
5223,Emory University Hospital,2017-02-24,647963,18918,NaT,Medical/Surgical Inpatient Unit,30.0,Female,Xavier University Of Louisiana,Bsn,...,<NA>,No,<NA>,No,NaT,NaN,<NA>,<NA>,Xavier University Of Louisiana,25792
5224,Emory University Hospital Midtown,2024-10-25,0474420,18919,2024-10-14,Orthopedic Inpatient Unit,39.0,Female,York Technical College,Adn/Asn,...,<NA>,No,<NA>,No,NaT,NaN,<NA>,<NA>,York Technical College,25793

In [35]:

df_clean.columns = (
    df.columns
    .str.strip()
    .str.lower()
)
df_clean
print(df_clean.columns)

ValueError: Length mismatch: Expected axis has 21 elements, new values have 23 elements

In [37]:
df_clean["age"] = pd.to_numeric(df_clean["age"], errors="coerce")

# Remove age >= 65 and missing ages

df_clean = df_clean[(df_clean["age"] < 65) & (df_clean["age"].notna())]

# Keep only affiliated schools

valid_schools = {
    "Abraham Baldwin Agricultural Program (Abac)",
    "Albany State University",
    "American Sentinel College",
    "Atlanta Technical College",
    "Auburn University School Of Nursing Main Campus",
    "Augusta University",
    "Baylor University",
    "Brenau University",
    "Capella University",
    "Chamberlain College Of Nursing",
    "Columbus State University",
    "Dalton State College",
    "Duke University",
    "Emory University",
    "Fort Valley State University",
    "Georgia College And State University",
    "Georgia Gwinnett College",
    "Georgia Highlands College",
    "Georgia State University",
    "Gordon State College",
    "Grand Canyon",
    "Herzing University",
    "Indiana University",
    "Jacksonville University",
    "Kennesaw State University",
    "Mercer University",
    "Middle Georgia State",
    "Reinhardt University",
    "South College Atlanta",
    "Thomas University",
    "University Of Alabama Birmingham",
    "University Of Cincinnati",
    "University Of North Georgia",
    "University Of Pittsburgh",
    "University Of South Carolina",
    "University Of Tennessee",
    "University Of West Georgia",
    "Vanderbilt University",
    "Walden University",
    "Western Governor'S University",
    "Xavier University"
}

# normalize for matching
df_clean["education_clean"] = df_clean["education"].str.title()

df_clean = df_clean[df_clean["education_clean"].isin(valid_schools)]

#Remove rows where previous healthcare experience is NOT NaN

df_clean = df_clean[df_clean["previous health care work experience"].isna()]

# Drop column

if "termination updated by" in df_clean.columns:
    df_clean = df_clean.drop(columns=["termination updated by"])
df_clean

if "education" in df_clean.columns:
    df_clean = df_clean.drop(columns=["education"])
df_clean

if "education (cleaned)" in df_clean.columns:
    df_clean = df_clean.drop(columns=["education (cleaned)"])
df_clean

KeyError: 'education'

In [34]:
df_clean.to_csv("Vizient_CLEANED_FINAL.csv", index=False)

print("Final shape:", df_clean.shape)
print(df_clean.head())

Final shape: (2059, 21)
                         organization cohort date nurse id  deid_names  \
1   Emory University Hospital Midtown  2025-08-08  0480100       13696
16          Emory University Hospital  2022-10-14  0457429       13711
21             Emory Decatur Hospital  2025-04-01  0476508       13716
23          Emory University Hospital  2024-10-28  0448283       13718
24          Emory University Hospital  2024-10-28  0465066       13719

   employment start date                        type of unit   age  gender  \
1             2025-08-04     Medical/Surgical Inpatient Unit  23.0  Female
16            2022-11-07           Orthopedic Inpatient Unit  27.0    Male
21            2025-03-17                Emergency Department  24.0  Female
23            2024-10-14  Medical/Surgical Intermediate Unit  26.0  Female
24            2024-10-14                     Transplant Unit  24.0  Female

   nursing degree received            gpa  ...  \
1                      Bsn  3.5 And Above  ...
16                     Bsn     3.0 - 3.49  ...
21                 Adn/Asn     3.0 - 3.49  ...
23                 Adn/Asn     3.0 - 3.49  ...
24                     Bsn     3.0 - 3.49  ...

   previous health care work experience leave type of leave termination  \
1                                  <NA>    No          <NA>          No
16                                 <NA>    No          <NA>         Yes
21                                 <NA>    No          <NA>          No
23                                 <NA>    No          <NA>          No
24                                 <NA>    No          <NA>          No

   termination date    tenure  \
1               NaT       NaN
16       2023-09-20  0.868493
21              NaT       NaN
23              NaT       NaN
24              NaT       NaN

                                 termination reason     id  \
1                                              <NA>  20576
16  Obtained Position With A More Desirable Commute  20590
21                                             <NA>  20595
23                                             <NA>  20597
24                                             <NA>  20598

            education_clean gpa_numeric
1   Albany State University        3.75
16  Albany State University        3.25
21  Albany State University        3.25
23  Albany State University        3.25
24  Albany State University        3.25

[5 rows x 21 columns]

In [38]:
gpa_map = {
    "3.5 And Above": 3.75,
    "3.0 - 3.49": 3.25,
    "2.5 - 2.99": 2.75,
    "2.0 - 2.49": 2.25,
    "Below 2.0": 1.75
}

df_clean["gpa"] = (
    df["gpa"]
    .astype(str)
    .str.strip()
    .str.title()
)


df_clean["gpa_numeric"] = df_clean["gpa"].map(gpa_map)

df_clean = df_clean[df_clean["gpa_numeric"].notna()]

avg_gpa_by_school = (
    df_clean
    .groupby("education_clean)")["gpa_numeric"]
    .mean()
    .sort_values(ascending=False)
)

print(avg_gpa_by_school)

avg_gpa_df = avg_gpa_by_school.reset_index()
avg_gpa_df.columns = ["School", "Average GPA"]

print(avg_gpa_df)

counts = df_clean.groupby("education_clean").size()

result = avg_gpa_by_school.to_frame("Average GPA")
result["Count"] = counts

print(result.sort_values("Average GPA", ascending=False))

avg_gpa_df.to_csv("avg_gpa_by_school.csv", index=False)

KeyError: 'education_clean)'